packages:
  # all packages in direct subdirs of packages/
  - 'apps/*'
  - 'extensions/*'
  # all packages in subdirs of components/
  #- 'components/**'
  # exclude packages that are inside test directories
  #- '!**/test/**'